### ISSUE TITLE
Licence?? 

### ISSUE THREAD

**Issue by naok62** [MagicMikeAndCo/RadioListenerFinal#1]
Salut, 

dans le cadre d'un exercice universitaire je suis à la recherche d'un projet dans lequel je pourrais creer une issue et un merge positif, j'ai remarqué que dans le projet il n'y avait pas de fichier licence, puis-je proposer mon aide  à la réalisation de ce fichier?

Merci.

**Comment by Tyrron** [comment]
![booboo](http://i.giphy.com/4LTGEdPZvDwPwscpRDsQ.gif)
